# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

## Project team
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->

[Saranjeet Kaur Bhogal](https://profiles.imperial.ac.uk/s.bhogal) will be the lead developer for this project. She is a Research Software Engineer in the [central Research Software Engineering team](https://www.imperial.ac.uk/admin-services/ict/self-service/research-support/rcs/service-offering/research-software-engineering/) at Imperial College London and has experience in developing R packages and contributing to the R community. She will be responsible for developing the proposed R package and coordinating with stakeholders, in particular the [R Contribution Working Group (RCWG)](https://contributor.r-project.org/working-group), to ensure the package integrates with their translation process. Saranjeet is a member of the RCWG, where she has co-authored the [R Development Guide](https://contributor.r-project.org/rdevguide/) and has also contributed to translations of R messages to Hindi. She has also contributed to the R community through the [R Dev Days](https://contributor.r-project.org/events/r-dev-days/).

## Contributors
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->

The following people (in alphabetical order) have contributed to the proposal:

- [Diego Alonso Alvarez](https://profiles.imperial.ac.uk/d.alonso-alvarez)
- [Gergely Daróczi](https://daroczig.github.io/)
- [Heather Turner](https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/turner/)
- [Maëlle Salmon](https://masalmon.eu/)
- [Michael Chirico](https://github.com/michaelchirico)
- [Yanina Bellini Saibene](https://yabellini.netlify.app/)

## Consulted
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

The following people (in alphabetical order) have been consulted and have provided feedback on the proposal:

- [Diego Alonso Alvarez](https://profiles.imperial.ac.uk/d.alonso-alvarez)
- [Gergely Daróczi](https://daroczig.github.io/)
- [Heather Turner](https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/turner/)
- [Maëlle Salmon](https://masalmon.eu/)
- [Michael Chirico](https://github.com/michaelchirico)
- [Yanina Bellini Saibene](https://yabellini.netlify.app/)

