# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The project will be setup as a GitHub repository and the various steps for the development will be opened as issues on GitHub. Development will take place and be tracked by creating pull requests associated to the issues. Appropriate license will be chosen for the package. The contributors to the project will be acknowledged using the all contributors bot on GitHub. The work on the project will be regularly reported to the community through the [R Contribution Working Group](https://contributor.r-project.org/working-group) meetings and occasionally through the [R Contributor Office Hours](https://contributor.r-project.org/events/office-hours/).

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

The work on the package development is scheduled for July - November 2025. 

| Timeline | Tasks and milestones |
|--------|--------------------|
| First half of July 2025    | Setup the technical infrastructure and create issues on the GitHub repo|
| Mid July 2025 | Present the initial setup to the RCWG and get feedback|
| Second half of July 2025 - September 2025 | Development work |
| End of September 2025 | Mid project presentation to the RCWG and get feedback|
| October 2025 - November 2025 | Continue the development work based on the feedback|
| End of November 2025 | Final presentation to the RCWG, write and share a blog post about the work|

The development work will be associated with milestones and deliverables which will be tracked through GitHub. A final blog post will be published to share the work done along with social media announcements. If possible, the work will also be publicised at relevant events, including R-Ladies+ and RUG meetups.

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

The project will be promoted through the RCWG to ensure that the R community is aware of the project. Regular updates will be provided to the R community on the progress of the project. Feedback will be sought from the community to ensure that the package meets the needs of the users. The updates will be provided through regular blog posts and announcements on social media platforms. The project will also be discussed with local R-Ladies+ and R User Groups.